{{- if not .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared-ingress-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared-ingress-router.labels" . | nindent 4 }}
type: Opaque
stringData:
  accountId: {{ required "cloudflare.accountId is required" .Values.cloudflare.accountId | quote }}
  tunnelId: {{ required "cloudflare.tunnelId is required" .Values.cloudflare.tunnelId | quote }}
  apiToken: {{ required "cloudflare.apiToken is required" .Values.cloudflare.apiToken | quote }}
{{- end }}
